review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

supermemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls'))
]

web/urls.py
from django.urls import path

from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_new_review_item', views.add_new_review_item, name='add_new_review_item'),
    path('edit_existing_review_item', views.edit_existing_review_item, name='edit_existing_review_item'),
    path('reviewed', views.reviewed, name='reviewed'),
    path('review_list', views.review_list, name='review_list'),
    path('get_raw_review_item_data', views.get_raw_review_item_data, name='get_raw_review_item_data'),
    path('render_markdown', views.render_markdown, name='render_markdown'),
]

web/models.py
from django.db import models
from django.conf import settings

class ReviewItem(models.Model):
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    caption = models.TextField()
    location = models.TextField(blank=True, null=True, help_text="e.g. URL or book title")
    notes = models.TextField(blank=True, null=True, help_text="e.g. section title or book page number")
    is_hyperlink = models.BooleanField(help_text="Is location a live hyperlink?")

    # SuperMemo variables
    interval = models.IntegerField('Next review interval')
    repetitions = models.IntegerField('Successful review streak')
    easiness = models.FloatField('Easiness')
    next_review = models.DateField('Next review')

    def save_model(self, request, obj, form, change):
        obj.added_by = request.user
        super().save_model(request, obj, form, change)

    def __str__(self):
        return self.caption

web/views.py
import datetime
import json

from  supermemo2 import SMTwo

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from web.models import ReviewItem
from django.shortcuts import redirect
from operator import attrgetter
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string

from web.utils import conversion_to_hyperlink
from web.logic import items_due

@login_required
@require_http_methods(["GET"])
def index(request):
    return render(request, 'web/index.html')

@login_required
@require_http_methods(["GET"])
def review_list(request):
    to_review = items_due(request.user, datetime.date.today())
    return render(request, 'web/review_list.html', {'review_items': to_review})


@login_required
@require_http_methods(["GET"])
def render_markdown(request):
    rendered = render_to_string('web/render_markdown.html', {'content': request.GET["markdown"]}).strip()
    return JsonResponse({ 'rendered': rendered })


@login_required
@require_http_methods(["GET"])
def get_raw_review_item_data(request):
    item = ReviewItem.objects.get(added_by=request.user, id=request.GET['review_item_id'])
    data = { "caption": item.caption, "location": item.location, "notes": item.notes }
    return JsonResponse(data)

@login_required
@require_http_methods(["POST"])
def add_new_review_item(request):
    caption = request.POST['caption']

    if not caption:
        return HttpResponse(status=400, reason='caption is empty')

    # arbitrarily setting initial quality to 3
    sm = SMTwo.first_review(quality=3)

    conv = conversion_to_hyperlink(request.POST['location'])
    sanitized_location = conv(request.POST['location']) if conv is not None else request.POST['location']
    #new_repetitions is 2 at start, feels wrong
    ReviewItem.objects.create(added_by=request.user, caption=caption, location=sanitized_location,
                              is_hyperlink=conv is not None, notes=request.POST['notes'], interval=sm.interval,
                              repetitions=sm.repetitions, next_review=sm.review_date, easiness=sm.easiness)
    return HttpResponse()

@login_required
@require_http_methods(["POST"])
def edit_existing_review_item(request):
    caption = request.POST['caption']

    if not caption:
        return HttpResponse(status=400, reason=f'caption is empty')

    item = ReviewItem.objects.get(added_by=request.user, id=request.POST['review_item_id'])

    # If location hasn't changed, preserve the original value of is_hyperlink - if something was a live hyperlink
    # at creation then it is still a hyperlink now (but perhaps one gone bad).
    if item.location != request.POST['location']:
        conv = conversion_to_hyperlink(request.POST['location'])
        sanitized_location = conv(request.POST['location']) if conv is not None else request.POST['location']
        item.is_hyperlink = conv is not None
        item.location = sanitized_location
    item.caption = caption
    item.location = request.POST['location']
    item.notes = request.POST['notes']
    item.save()

    return HttpResponse()

@login_required
@require_http_methods(["POST"])
def reviewed(request):
    quality = int(request.POST['quality'])
    if quality < 0 or quality > 5:
        return HttpResponse(status=400, reason='Invalid recall quality: ' + quality)

    item = ReviewItem.objects.get(added_by=request.user, id=request.POST['review_item_id'])
    today = datetime.date.today()

    # Take current review's quality and infer new values for review variables:
    #  - repetitions: quality <3 breaks the streak and resets it to 1, I think
    #  - easiness is lowered if quality is low
    #  - interval is shortened if quality is low
    sm = SMTwo(easiness=item.easiness, interval=item.interval, repetitions=item.repetitions)
    reviewed = sm.review(quality, today)

    item.interval = reviewed.interval
    item.repetitions = reviewed.repetitions
    item.easiness = reviewed.easiness
    item.next_review = reviewed.review_date
    item.save()

    return JsonResponse({ 'items_due_count': len(items_due(request.user, today)) })

web/templates/web/edit_new_resource.html
{% load static %}

<style>
    #edit-resource-form label, #edit-resource-form input { display:block; }
    input.text { margin-bottom:12px; width:100%; padding: .4em; }
    textarea { margin-bottom:12px; width:100%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }

    #plus {
        cursor: pointer;
        width: 0.75in;
        position: fixed;
        bottom: 1em;
        right: 1em;
    }
</style>

<script type="text/javascript">

    function updateTips( t ) {
        const tips = $(".validateTips");
        tips.text(t).addClass("ui-state-highlight");
        setTimeout(function() {
            tips.removeClass("ui-state-highlight", 1500);
        }, 500);
    }

    function checkNotEmpty(input, name) {
        if (input.val().length == 0) {
            input.addClass( "ui-state-error" );
            updateTips(name + " cannot be empty");
            return false;
        } else {
            return true;
        }
    }

    function validateAndSendNewResource(dialog) {
        //allFields.removeClass("ui-state-error");

        const valid = checkNotEmpty($("#caption"), "Caption");

        if (valid) {
            $.post('{% url 'web:add_new_resource' %}', $('#edit-resource-form').serialize())
                .done(function() { alertify.success('Success'); })
                .fail(function() { alertify.error('Error'); });
            dialog.dialog("close");
        }

        return valid;
    }

    function validateAndEditExistingResource(dialog, res_id, onSuccess) {
        //allFields.removeClass("ui-state-error");

        const valid = checkNotEmpty($("#caption"), "Caption");

        if (valid) {
            var values = $('#edit-resource-form').serialize();
            values += ('&resource_id=' + res_id);
            $.post('{% url 'web:edit_existing_resource' %}', values)
                .done(function() { onSuccess(); alertify.success('Success'); })
                .fail(function() { alertify.error('Error'); });
            dialog.dialog("close");
        }

        return valid;
    }

    // Creates a jQuery UI dialog based on the #dialog-form. It contains a Cancel button and a customisable
    // "action" button (e.g. for adding a new iterm or editing an existing one)
    function setupEditDialog(actionButtonLabel, actionButtonAction) {
        var dialog, form,
            caption = $("#caption"),
            location = $("#location"),
            notes = $("#notes"),
            allFields = $( [] ).add(caption).add(location).add(notes);

        var options = {
          autoOpen: false,
          height: 440,
          width: 350,
          modal: true,
          buttons: {
            Cancel: function() {
              dialog.dialog("close");
            }
          },
          open: function() {
            $("#validateTips").html("");
          },
          close: function() {
            form[0].reset();
            allFields.removeClass("ui-state-error");
          }
        }

        options.buttons[actionButtonLabel] = actionButtonAction;
        dialog = $("#dialog-form").dialog(options);
        form = dialog.find("form");

        return dialog;
    };

    function addNewReviewItem() {
        var dialog = setupEditDialog("Add", function() { return validateAndSendNewResource(dialog); });
        dialog.dialog("open");
    }

    function editReviewItem(item_id) {
        // in order to edit an item, we need to get raw data from the backend (esp. markdown for notes)
        $.get("{% url 'web:get_raw_resource_data' %}", { resource_id: item_id, csrfmiddlewaretoken: "{{ csrf_token }}" },
            function(data) {
                $("#caption").val(data.caption);
                $("#location").val(data.location);
                $("#notes").val(data.notes);
                var dialog = setupEditDialog("OK", function() {
                    return validateAndEditExistingResource(dialog, item_id, loadReviewList);
                });
                dialog.dialog("open");
            });
    }

</script>

<!-- Icon by Robert Walsh via https://www.iconfinder.com/icons/619553/add_create_new_plus_icon -->
<img id="plus" src="{% static 'web/add_blue.png' %}" onclick="addNewReviewItem()">

<!-- display: none so that it doesn't flash on the screen before dialog() doesn't hide it -->
<div id="dialog-form" title="Add new review resource" style='display: none;'>
    <p class="validateTips" id="validateTips"></p>

    <form class="edit-resource-form" id="edit-resource-form" autocomplete="off">
        <fieldset>
            {% csrf_token %}
            <label for="caption">Caption</label>
            <input type="text" name="caption" id="caption" value="" class="text ui-widget-content ui-corner-all">
            <label for="location">Location</label>
            <input type="text" name="location" id="location" value="" class="text ui-widget-content ui-corner-all">
            <label for="notes">Notes</label>
            <textarea form="edit-resource-form" name="notes" id="notes" rows=5 value="" class="text ui-widget-content ui-corner-all"></textarea>
        </fieldset>
    </form>
</div>

web/templates/web/edit_new_review_item.html
{% load static %}

<style>
    #edit-review-item-form label, #edit-review-item-form input { display:block; }
    #edit-review-item-form label { margin-bottom: 0.2em; }
    input.text { margin-bottom:12px; width:100%; padding: .4em; flex: 0; box-sizing: border-box; }
    #edit-review-item-form { flex-grow:1; display: flex; flex-direction: column; }
    #dialog-form { display: flex; flex-direction: column; }
    fieldset { padding:0; border:0; flex-grow: 1; display: flex; flex-direction: column; }
    {% comment %} notes box takes up all remaining space {% endcomment %}
    #notes { margin-bottom:12px; width:100%; padding: .4em; flex-grow:1; box-sizing: border-box; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
    .preview-edit-button { margin-bottom: 12px; }

    #plus {
        cursor: pointer;
        width: 0.75in;
        position: fixed;
        bottom: 1em;
        right: 1em;
    }
</style>

<script type="text/javascript">
    'use strict';

    function updateTips( t ) {
        const tips = $(".validateTips");
        tips.text(t).addClass("ui-state-highlight");
        setTimeout(function() {
            tips.removeClass("ui-state-highlight", 1500);
        }, 500);
    }

    function checkNotEmpty(input, name) {
        if (input.val().length == 0) {
            input.addClass( "ui-state-error" );
            updateTips(name + " cannot be empty");
            return false;
        } else {
            return true;
        }
    }

    function validateAndSendNewReviewItem(dialog) {
        //allFields.removeClass("ui-state-error");

        const valid = checkNotEmpty($("#caption"), "Caption");

        if (valid) {
            $.post('{% url 'web:add_new_review_item' %}', $('#edit-review-item-form').serialize())
                .done(function() { alertify.success('Added'); })
                .fail(function() { alertify.error('Error'); });
            dialog.dialog("close");
        }

        return valid;
    }

    function validateAndEditExistingReviewItem(dialog, item_id, onSuccess) {
        //allFields.removeClass("ui-state-error");

        const valid = checkNotEmpty($("#caption"), "Caption");

        if (valid) {
            const values = $('#edit-review-item-form').serialize() + ('&review_item_id=' + item_id);
            $.post('{% url 'web:edit_existing_review_item' %}', values)
                .done(function() { onSuccess(); })
                .fail(function() { alertify.error('Error'); });
            dialog.dialog("close");
        }

        return valid;
    }

    // Creates a jQuery UI dialog based on the #dialog-form. It contains a Cancel button and a customisable
    // "action" button (e.g. for adding a new item or editing an existing one)
    function setupEditDialog(dialogTitle, actionButtonLabel, actionButtonAction) {
        let dialog, form;
        const caption = $("#caption"),
              location = $("#location"),
              notes = $("#notes"),
              allFields = $( [] ).add(caption).add(location).add(notes);

        const options = {
          autoOpen: false,
          // jqueryUI dialog doesn't like setting height to 95%
          height: $(window).height() * 0.95,
          width: "95%",
          modal: true,
          buttons: {
            Cancel: function() {
              dialog.dialog("close");
            }
          },
          open: function() {
            $("#validateTips").html("");
          },
          close: function() {
            form[0].reset();
            switch_to_edit();
            allFields.removeClass("ui-state-error");
          }
        }

        options.buttons[actionButtonLabel] = actionButtonAction;
        options.position = { my: "top", at: "top+10", of: window };
        dialog = $("#dialog-form").dialog(options);
        dialog.dialog("option", "title", dialogTitle);
        form = dialog.find("form");

        return dialog;
    };

    function addNewReviewItem() {
        const dialog = setupEditDialog("Add review item", "Add",
                                     function() { return validateAndSendNewReviewItem(dialog); });
        dialog.dialog("open");
    }

    function editReviewItem(item_id) {
        // in order to edit an item, we need to get raw data from the backend (esp. markdown for notes)
        $.get("{% url 'web:get_raw_review_item_data' %}", { review_item_id: item_id, csrfmiddlewaretoken: "{{ csrf_token }}" },
            function(data) {
                $("#caption").val(data.caption);
                $("#location").val(data.location);
                $("#notes").val(data.notes);
                const dialog = setupEditDialog("Edit review item", "OK", function() {
                    return validateAndEditExistingReviewItem(dialog, item_id, loadReviewItemsList);
                });
                dialog.dialog("open");
            });
    }

    function switch_to_edit() {
        $('#edit-button').hide();
        $('#preview-button').show();

        $('#preview').hide();
        $('#notes').show();
        $('#preview').html('');
    }

    function switch_to_preview() {
        let markdown = $('#notes').val();
        $('#preview-button').attr('disabled', 'disabled');

        $.get('{% url 'web:render_markdown' %}', { 'markdown': markdown, 'csrfmiddlewaretoken': '{{ csrf_token }}' } )
            .done((data) => {
                $('#preview').html(data.rendered);
                MathJax.typesetPromise($('#preview')).then(() => {
                    $('#notes').hide();
                    $('#preview').show();
                    $('#preview-button').hide();
                    $('#edit-button').show();
                    $('#preview-button').removeAttr('disabled');
                });
            })
            .fail(() => {
                $('#preview-button').removeAttr('disabled');
                alertify.error('Error');
            });
    }

</script>

<!-- Icon by Robert Walsh via https://www.iconfinder.com/icons/619553/add_create_new_plus_icon -->
<img id="plus" src="{% static 'web/add_blue.png' %}" onclick="addNewReviewItem()">

<!-- display: none so that it doesn't flash on the screen before dialog() doesn't hide it -->
<div id="dialog-form" title="Add new review item" style='display: none;'>
    <p class="validateTips" id="validateTips"></p>

    <form class="edit-review-item-form" id="edit-review-item-form" autocomplete="off">
        <fieldset>
            {% csrf_token %}
            <label for="caption">Caption</label>
            <input type="text" name="caption" id="caption" value="" class="text ui-widget-content ui-corner-all">
            <label for="location">Location</label>
            <input type="text" name="location" id="location" value="" class="text ui-widget-content ui-corner-all">
            <label for="notes">Notes</label>
            <div>
                <button class="preview-edit-button" id="edit-button" style='display: none;' type="button" onclick="switch_to_edit()">Edit</button>
                <button class="preview-edit-button" id="preview-button" type="button" onclick="switch_to_preview()">Preview</button>
            </div>
            <div id="preview" style='display: none;'></div>
            <textarea form="edit-review-item-form" name="notes" id="notes" value="" class="text ui-widget-content ui-corner-all tab-support"></textarea>
        </fieldset>
    </form>
</div>

web/templates/web/help.html
<div id="help-div" style='display: none;'>
    <h1>Markdown</h1>

    <h2>MathJax</h2>
    <h3>Inline</h3>
    <code>$\frac{1}{2}$</code> - if you don't want math typesetting, need to escape $: <code>That'll be \$50</code>
    <h3>Block</h3>
<pre>
$$
\sum_{i=1}^{k}{x^i}
$$</pre>

    <h2>Highlighted code blocks</h2>
<pre>
```C++
int main() {
    return 0;
}
```</pre>

    or

<pre>
~~~C++
int main() {
    return 0;
}
~~~</pre>

    <h2>Folding blocks</h2>

    Using <code>pymdownx.details</code> extension. Syntax:

    <pre>
??? "Multi word summary needs to be in quotes"
    Content must be indented</pre>

    Folding code blocks also work:

    <pre>
??? Example
    ~~~C++
    int main() {
        return 0;
    }
    ~~~</pre>
</div>

web/templates/web/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <title>Review</title>
  <!-- favicon generated from https://favicon.io/emoji-favicons/brain/ -->
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'web/favicon.ico' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>
    select, .edit-button {
        height: 2.3em;
        margin: 0.2em;
    }

    hr {
        border: 0;
        border-top: 1px solid #eeeeee;
    }

    body {
        padding: 0.5em;
    }
  </style>
</head>

<link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'web/code_styles.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'web/alertify/css/themes/default.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'web/alertify/css/alertify.min.css' %}">

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<script type="text/javascript" src="{% static 'web/jquery-3.6.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'web/alertify/alertify.min.js' %}"></script>

<script src="{% static 'web/jquery-ui-1.13.1.dialog/jquery-ui.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'web/jquery-ui-1.13.1.dialog/jquery-ui.min.css' %}">

<script type="text/javascript">
window.MathJax = {
    tex: {
        // enable single $'s to delimit inline math for MathJax
        inlineMath: [['$', '$'], ['\\(', '\\)']]
    }
};

'use strict';
function showHelp() {
    const options = {
      autoOpen: false,
      // jqueryUI dialog doesn't like setting height to 95%
      height: $(window).height() * 0.95,
      width: "95%",
      modal: true,
      title: "Help"
    }
    let dialog = $("#help-div").dialog(options);
    dialog.dialog("open");
}

function reviewed(review_item_id) {
    const quality = document.getElementById("quality_" + review_item_id).value;
    $.post("{% url 'web:reviewed' %}", {review_item_id : review_item_id, quality : quality, csrfmiddlewaretoken: "{{ csrf_token }}"}, function(data) {
        if (data.items_due_count == 0) {
            $("#review_list_header").html("All done for today");
        }
    });
}

function loadReviewItemsList() {
    $.get("{% url 'web:review_list' %}", { csrfmiddlewaretoken: "{{ csrf_token }}" },
        function(data) {
            $("#review-list").html(data);
            // Need to re-run MathJax typesetting after the list of review items is loaded - it would have run
            // automatically at page load when there was nothing there.
            // Only running MathJax here relies on this function being called every time something changes. If we end up
            // e.g. reloading individual review items, this will have to change.
            // Also, not doing anything fancy with async typesetting (see
            // http://docs.mathjax.org/en/latest/advanced/typeset.html), should be sufficient for now.
            console.log("typesetting math");
            MathJax.typeset($('html'));
        });
}

$(window).bind("load", function () {
    loadReviewItemsList();
});

</script>

<body>

<form action="accounts/logout">
    <input type="submit" value="Logout" style="float: right; margin-left: 0.4em;">
</form>
<button id="help-button" style="float: right;" onclick="showHelp()">Help</button>


<div id="review-list"></div>

{% include "web/tab_support.html" %}
{% include "web/edit_new_review_item.html" %}
{% include "web/help.html" %}

</body>
</html>

web/templates/web/list_pending.html
<!-- TODO: Use jQuery UI's Accordion? -->

<div id="review_items">
{% if resources %}
    <h2>Today's review:</h2>
    {% for res in resources %}
        {% include 'web/review_item.html' with data=res %}
    {% endfor %}
{% else %}
    <h2>Nothing for today</h2>
{% endif %}
</div>

web/templates/web/render_markdown.html
{% load markdown_extras %}

{% autoescape off %}
    {{ content | markdown }}
{% endautoescape %}

web/templates/web/review_item.html
{% load markdown_extras %}

<div class="review_item" id="{{ data.id }}">
    <div class="review_item_caption">
        {% if data.is_hyperlink %}
            <h3><a target="_blank" rel="noopener noreferrer" href='{{ data.location }}'>{{ data.caption }}</a></h3>
        {% else %}
            <h3>{{ data.caption }}</h3>
        {% endif %}
    </div>
    {% if data.location and not data.is_hyperlink or data.notes %}
        <div class="review_item_details">
            <!-- don't include anything for empty location (esp. the <br>) -->
            {% if not data.is_hyperlink and data.location %}
                <span class=review_item_location_non_hyperlink>{{ data.location }}</span><br>
            {% endif %}
            {% if data.notes %}
                {% autoescape off %}
                    {{ data.notes | markdown }}
                {% endautoescape %}
            {% endif %}
        </div>
    {% endif %}

    <select name="quality" class="review_quality_select" id="quality_{{ data.id }}" onchange="reviewed({{ data.id }}); $('#{{ data.id }}').toggle('medium')">
      <option disabled selected value="-1">Review...</option>
      <option value="0">complete blackout</option>
      <option value="1">incorrect response; the correct one remembered</option>
      <option value="2">incorrect response; correct one easy to recall</option>
      <option value="3">correct response, recalled with serious difficulty</option>
      <option value="4">correct response after a hesitation</option>
      <option value="5">perfect response</option>
    </select>
    <button class="edit-button" onclick="editReviewItem({{ data.id }})">Edit</button>
    <hr>
</div>

web/templates/web/review_list.html
<!-- TODO: Use jQuery UI's Accordion? -->

<div id="review_items">
{% if review_items %}
    <h2 id="review_list_header">Today's review:</h2>
    {% for item in review_items %}
        {% include 'web/review_item.html' with data=item %}
    {% endfor %}
{% else %}
    <h2>Nothing for today</h2>
{% endif %}
</div>

web/templates/web/tab_support.html
<script type="text/javascript">
    const tab = "    ";
    // after: https://stackoverflow.com/a/45396754/194825
    $(function() {
        var enabled = true;
        $("textarea.tab-support").keydown(function(e) {

            // Escape key toggles tab on/off
            if (e.keyCode==27)
            {
                enabled = !enabled;
                return false;
            }

            // Enter Key?
            if (e.keyCode === 13 && enabled)
            {
                // selection?
                if (this.selectionStart == this.selectionEnd)
                {
                    // find start of the current line
                    var sel = this.selectionStart;
                    var text = $(this).val();
                    while (sel > 0 && text[sel-1] != '\n')
                    sel--;

                    var lineStart = sel;
                    while (text[sel] == ' ' || text[sel]==tab)
                    sel++;

                    if (sel > lineStart)
                    {
                        // Insert carriage return and indented text
                        document.execCommand('insertText', false, "\n" + text.substr(lineStart, sel-lineStart));

                        // Scroll caret visible
                        this.blur();
                        this.focus();
                        return false;
                    }
                }
            }

            // Tab key?
            if(e.keyCode === 9 && enabled)
            {
                // selection?
                if (this.selectionStart == this.selectionEnd)
                {
                    // These single character operations are undoable
                    if (!e.shiftKey)
                    {
                        document.execCommand('insertText', false, tab);
                    }
                    else
                    {
                        var text = this.value;
                        if (this.selectionStart > 0 && text[this.selectionStart-1]==tab)
                        {
                            document.execCommand('delete');
                        }
                    }
                }
                else
                {
                    // Block indent/unindent trashes undo stack.
                    // Select whole lines
                    var selStart = this.selectionStart;
                    var selEnd = this.selectionEnd;
                    var text = $(this).val();
                    while (selStart > 0 && text[selStart-1] != '\n')
                        selStart--;
                    while (selEnd > 0 && text[selEnd-1]!='\n' && selEnd < text.length)
                        selEnd++;

                    // Get selected text
                    var lines = text.substr(selStart, selEnd - selStart).split('\n');

                    // Insert tabs
                    for (var i=0; i<lines.length; i++)
                    {
                        // Don't indent last line if cursor at start of line
                        if (i==lines.length-1 && lines[i].length==0)
                            continue;

                        // Tab or Shift+Tab?
                        if (e.shiftKey)
                        {
                            if (lines[i].startsWith(tab))
                                lines[i] = lines[i].substr(tab.length);
                            else if (lines[i].startsWith("    "))
                                lines[i] = lines[i].substr(4);
                        }
                        else
                            lines[i] = tab + lines[i];
                    }
                    lines = lines.join('\n');

                    // Update the text area
                    this.value = text.substr(0, selStart) + lines + text.substr(selEnd);
                    this.selectionStart = selStart;
                    this.selectionEnd = selStart + lines.length;
                }

                return false;
            }

            enabled = true;
            return true;
        });
    });
</script>